name: Telegram Deploy Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        uses: kekedaine/telegram-action@v5.0.8
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_POXME }}
          TELEGRAM_CHAT: "@proofxme"
        with:
          message: "hello world"
          parse_mode: "html"
