name: Telegram Notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Telegram
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_POXME }}/sendMessage" \
        -H "Content-Type: application/json" \
        --data-raw '{
          "chat_id": "@proofxme",
          "parse_mode": "HTML",
          "text": "<strong>Event:</strong> ${{ github.event_name }}<br><strong>Repository:</strong> ${{ github.repository }}<br><strong>Actor:</strong> ${{ github.actor }}<br><strong>Commit Message:</strong> ${{ github.event.head_commit.message }}<br>"
        }'
